### ISSUE TITLE
Azure CPI needs a new ways to deploy VMs

### ISSUE THREAD

**Issue by metron2** [cloudfoundry/bosh-azure-cpi-release#643] opened 2021-11-04 21:17 UTC
### Versions (*please add them if you have more releases for this issue*)
CPI      Version:
BOSH     Version:
CF       Version:
Diego    Version:

### Stemcell
Version: n/a
Distro:
  - [x] Ubuntu (focal)
  - [ ] CentOS

### Environment
- Azure Environment:
  - [ X ] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
    - Version: (e.g. 1712 update or build number 180106.1)
  - [ ] Others:
- Location: (e.g. East US)
- Subscription ID:
- Resource Group Name:
- [ ] Use Managed Disks

### Issue Details
Bosh relies on this dead project, [WalaAgent](https://github.com/Azure/WALinuxAgent), to provision VMs. It looks like now azure wants you to use cloud init.

### Logs (*Please redact all sensitive information in your logs*)
Error message: {
  "startTime": "2021-11-04T20:24:26.4564949+00:00",
  "endTime": "2021-11-04T21:04:10.359853+00:00",
  "status": "Failed",
  "error": {
    "code": "OSProvisioningTimedOut",
    "message": "OS Provisioning failure has reached terminal state and is non-recoverable for VM '2d7392a7-9a39-41cd-9aa7-b2c2e7c9c68d'. Consider deleting and recreating this virtual machine. Also, make sure the image has been properly prepared (generalized).\r\n * Instructions for Windows: https://azure.microsoft.com/documentation/articles/virtual-machines-windows-upload-image/ \r\n * Instructions for Linux: https://azure.microsoft.com/documentation/articles/virtual-machines-linux-capture-image/. \r\n \r\nAdditional Details: OS Provisioning for VM '2d7392a7-9a39-41cd-9aa7-b2c2e7c9c68d' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later. Also, make sure the image has been properly prepared (generalized).\r\n * Instructions for Windows: https://azure.microsoft.com/documentation/articles/virtual-machines-windows-upload-image/ \r\n * Instructions for Linux: https://azure.microsoft.com/documentation/articles/virtual-machines-linux-capture-image/ \r\n * If you are deploying more than 20 Virtual Machines concurrently, consider moving your custom image to shared image gallery. Please refer to https://aka.ms/movetosig for the same."
  },

### Repro steps (*if necessary, delete otherwise*)
You can't build the focal image for azure (see [focal/master](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-focal/master) with the latest Wala agent. It looks like azure cpi will need to support cloud-init for newer OSes.

**Comment by bgandon** [comment] 2021-11-05 12:21
Sorry, but [focal/master](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-focal/master) is an experimental branch that is not supported.

Current work is focusing on the upcoming JJ with early experiments on Ubuntu Impish Indri going on these days. We still have a _lot_ of refactoring and non-regression testing to do before a proper JJ Stemcell can be released next spring.

If you have resources for continuing the early work by @StefanWutz on Ubuntu Focal, that would be fantastic and for this, you're welcome to contribute to the `bosh-linux-stemcell-builder` repo! 👍

Right now, I'm just closing this issue, as the Azure CPI is definitely not concerned.

**Comment by beyhan** [comment] 2021-11-08 15:36
This should be valid also for the JJ stemcell. @metron2 as you found this could you please open an issue for the https://github.com/cloudfoundry/bosh-linux-stemcell-builder so that we have this on our radar.

**Comment by beyhan** [comment] 2021-11-26 09:05
Hi @metron2,

add this point as investigation for the jammy stemcell. I don't see that the [WalaAgent](https://github.com/Azure/WALinuxAgent) is dead. I also couldn't find any indication from the Azure platform about that. There is only the described difference between the `walaagent` and `cloud-init` support in https://docs.microsoft.com/en-us/azure/virtual-machines/linux/using-cloud-init#what-is-the-difference-between-cloud-init-and-the-linux-agent-wala. Can you provide more information here?

**Comment by metron2** [comment] 2021-12-21 17:24
It's been a while @beyhan but I got an error with focal that the distribution wasn't supported, so I tried bumping WalaAgent to a newer version but it still failed to configure the VM. The python stack ended in an error in distrubtion.py.

Cloud-init is pretty universal now. I was just thinking if you have to do something different anyway why not move to something that's universal (I had never heard of the wala-agent before). https://cloudinit.readthedocs.io/en/latest/

**Comment by beyhan** [comment] 2021-12-22 09:03
@metron2 thank you for bringing this up. I have added this point as something to be looked into when we work on the new Jammy based stemcell. I will close this issue because this is not the right place to track this.

**Closed by beyhan** 2021-12-22 09:03 UTC
