### ISSUE TITLE
Timeout during Create VM 'Bosh::AzureCloud::AzureAsynInternalError'

### ISSUE THREAD

**Issue by ClaudiaBaur** [cloudfoundry/bosh-azure-cpi-release#360] opened 2018-01-10 14:37 UTC
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: preversion from https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/issues/345
BOSH     Version: 2.0.45-d208799-2017-10-28T00:31:53Z
CF       Version:
Diego    Version:

### Stemcell
Version:
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [ ] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [x] AzureStack
  - [ ] Others:
- Location: local
- Subscription ID:
- Resource Group Name:
- [ ] Use Managed Disks

### Issue Details
--- This issue looks in parts very similar to issue https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/issues/359 ---
I see this issue when deploying a larger component (cf. cf-diego,...) which creates several VMs in parallel (mostly also in parallel availability zones). Then bosh throws a timeout and the deployment hangs. 

As a workaround I can firstly only create the VMs of one availability zone and then in a second step I create all VMs. When splitting the deployment in two steps, most of the time it works. So this issue seems to be related to the load by creating several VMs in parallel.

Currently I deploy application-logging and I see this timeout again without a workaround.
The bosh deployment says:
![image](https://user-images.githubusercontent.com/20183811/34775365-32a88e08-f613-11e7-91d3-f583b45bcb9a.png)

When checking the task debug output, I see:
![image](https://user-images.githubusercontent.com/20183811/34775466-8652661e-f613-11e7-8fa7-8edef508d530.png)
![image](https://user-images.githubusercontent.com/20183811/34775757-8e824b28-f614-11e7-9177-52d0e75213fc.png)

In the Azure Stack portal, I see the VMs which have been created during the deployment in status failed, but they exist.
![image](https://user-images.githubusercontent.com/20183811/34776834-6fc4f984-f618-11e7-950a-6f3dff2cf49d.png)

The colleagues running the deployment on Azure reported a similar timeout issue to me.

**Comment by bingosummer** [comment] 2018-01-10 15:34
Could you please share how many VMs are created at the same time? And which releases are you deploying? I'd like to reproduce the issue from my side.

**Comment by ClaudiaBaur** [comment] 2018-01-10 16:11
for application-logging, we create 31 VMs in several availability sets (I stripped it down to one availability zone, normally we take several).
Here you see what has been created when running into the issue:
![image](https://user-images.githubusercontent.com/20183811/34782169-22c149c0-f628-11e7-8eea-b436ad708219.png)

**Comment by ClaudiaBaur** [comment] 2018-01-10 17:30
Unfortunately, we maintain private forks for some of the components, so that you might not be able to reproduce exactly my deployment. However, I can reproduce it with several configurations of cf, cf-diego and application-logging...
These are my releases which are deployed as part of application-logging:
releases:
  - name: logsearch # we're still on our fork!
    version: 207.0.0p7
  - name: logsearch-customization
    version: 4
  - name: aker
    version: 15
  - name: haproxy
    version: 6
  - name: routing
    version: 0.163.0
  - name: sleeve
    version: 16
  - name: telegraf
    version: 16
  - name: syslog-forwarder
    version: 5
    sha1: 83c7dc7a587363ecd734f18c61c1312ac0c37a5c
  - name: elk-enhance-boshrelease
    version: 1.1.1
  - name: redis
    version: 57

**Comment by bingosummer** [comment] 2018-01-11 03:13
Got it. Thanks. I will do some investigations.

I assume "preversion from #345" is `v29`. Right?

I should also point out that only 1 fault domain and 1 update domain are supported in Azure Stack.
https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-update-1712

**Comment by ClaudiaBaur** [comment] 2018-01-11 06:05
yes, I use your version 29.
I am aware of the limitation in fault and update domains and set them in the manifests to 1. They are created correctly

**Comment by bingosummer** [comment] 2018-01-15 05:39
@ClaudiaBaur 
After some investigations, I didn't find any clues about the `FabricNicAddError` in CPI. I think, it may be an Azure Stack platform issue. My suggestion is to contact Microsoft CSS and open a support ticket for assistance.

We can keep this issue open until your ticket is resolved by Microsoft CSS.

**Comment by ClaudiaBaur** [comment] 2018-01-16 10:03
Additional Remark...
This issue only occurs when creating much VMs in parallel. My environment is very slow, I stripped down the exactly same manifest from 31 (see image above) to 20 VMs to be created (see below). Then this part of the deployment worked...
![image](https://user-images.githubusercontent.com/20183811/34982297-50a1dd42-faaa-11e7-8e1a-bbec0934612d.png)
What I remarked is, that 3 VMs went temporarily in status failed during the deployment with the NIC issue described above:
![image](https://user-images.githubusercontent.com/20183811/34982394-8cf0edd8-faaa-11e7-9f6b-8cc3f7fb4d25.png)

But then they recovered by themselves and the deployment finished successfully. This really seems to be a timing issue because Azure Stack (here ASDK) needs too long to finish tasks. Is there kind of a wait parameter in bosh after creation of a VM I could increase?
I will reach out to the MS Azure Stack team, please let's keep this issue open until it is solved.

**Comment by bingosummer** [comment] 2018-04-16 03:35
@ClaudiaBaur Do you still hit the issue in the latest ASDK? Do you feel comfortable to close the issue now?

**Comment by ClaudiaBaur** [comment] 2018-04-16 06:53
Unfortunately we never came back to that point as the appliance behaves unstable. I would prefer to let this open until we can check it again.

**Comment by mifurm** [comment] 2018-08-21 19:59
have same issue :( for me it does not require many machines, one is enough to cause this error.

**Comment by gossion** [comment] 2018-08-22 01:27
@mifurm , I think it is intermittent platform issue. You can retry your deployment.

**Comment by h4xnoodle** [comment] 2019-10-17 23:41
Closing this issue due to inactivity and further evidence of the problem.

Thanks,
Rebecca

**Closed by h4xnoodle** 2019-10-17 23:41 UTC
Labels: azure-stack
